info:
  app.name: 'oauth2-server'
  app.version: '0.0.1-SNAPSHOT'
  app.title: 'OAuth2 Server'
  app.description: 'OAuth2 Server'
  
clientId: 'clientId'

server:
  contextPath: '/'
  port: 9000

ldap:
  url: 
  manager:
    dn: 
    password:
  user:
    search:
      base: 
      filter: 
    

spring:
  profiles: default, development
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db?createDatabaseIfNotExist=true
    username: oauthuser
    password: oauthuser
    driver-class-name: com.mysql.jdbc.Driver
    data-source-className: org.springframework.jdbc.datasource.DriverManagerDataSource
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    serialization:
      write-dates-as-timestamps: false
  allowedOriginsUrls:
    urls: http://localhost:8000, http://localhost:1110
---